Repository semantic-release/github, pull requests merged in 2018-12, with the labels that each got.

#137 Add scopes for personal access token
  README.md
Labels: docs, plugin:github

#140 when adding labels, expect labels array to be sent in request body for GHE support
  lib/success.js
  test/integration.test.js
  test/success.test.js
Labels: in progress

#142 build: remove unnecessary `docker` service in Travis
  .travis.yml
Labels: in progress, plugin:github

#141 chore(package): update semantic-release to version 16.0.0-beta
  .travis.yml
  README.md
  package.json
Labels: in progress, plugin:github

#145 fix: retrieve the branch name from `context.branch`
  README.md
  lib/fail.js
  lib/get-fail-comment.js
  test/fail.test.js
  test/get-fail-comment.test.js
  test/integration.test.js
Labels: bug, in progress, plugin:github

#146 fix: also add comment/label to open issues
  lib/success.js
  test/success.test.js
Labels: bug, in progress, plugin:github

#148 test: update ava to version 1.0.1
  package.json
  test/add-channel.test.js
  test/find-sr-issue.test.js
  test/get-client.test.js
  test/integration.test.js
  test/publish.test.js
  test/success.test.js
  test/verify.test.js
Labels: in progress
